# DAY 3 What made transformers so successful? like on a serious note the world is different now.


📌 Problem with Basic Seq2Seq Models (Without Attention)
In a traditional Sequence-to-Sequence (Seq2Seq) model (like an RNN-based encoder-decoder), the encoder processes the input sequence and compresses it into a single fixed-size context vector (the last hidden state).

🚨 What’s the issue?

This fixed-size context vector acts as a bottleneck—it must store all the information from the input sequence, even if the sequence is very long.
This leads to poor performance on long sentences, as the decoder struggles to retrieve earlier words.
The model tends to forget earlier parts of the sentence when generating longer outputs.

# The basic RNN cell equation can be represented as follows:
# h_t = tanh(W_hh * h_{t-1} + W_xh * x_t + b_h)
# where:
# - h_t is the hidden state at time t
# - h_{t-1} is the hidden state at time t-1
# - x_t is the input at time t
# - W_hh is the weight matrix for the hidden state
# - W_xh is the weight matrix for the input
# - b_h is the bias term
# 


#We are implementing a basic RNN cell in PyTorch. This will help us understand how an RNN processes a sequence over time.


In [1]:
import torch
import torch.nn as nn

In [2]:
import numpy as np

# Generate a simple sequence of numbers
sequence = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Prepare input-output pairs
X = []
y = []
for i in range(len(sequence) - 2):  # We need at least 2 previous values
    X.append([sequence[i], sequence[i+1]])  # Input is two previous numbers
    y.append(sequence[i+2])  # Target is the next number

# Convert to NumPy arrays
X = np.array(X)
y = np.array(y)

# Print dataset
print("Inputs:\n", X)
print("Targets:\n", y)


Inputs:
 [[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]
 [6 7]
 [7 8]
 [8 9]]
Targets:
 [ 3  4  5  6  7  8  9 10]


In [3]:
X

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6],
       [6, 7],
       [7, 8],
       [8, 9]])

In [4]:
y

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
import numpy as np

# Generate simple sequence data
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9]])
y = np.array([[3], [4], [5], [6], [7], [8], [9], [10]])

print("Inputs:\n", X)
print("Targets:\n", y)


Inputs:
 [[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]
 [6 7]
 [7 8]
 [8 9]]
Targets:
 [[ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [25]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)



Shape of X: (8, 2)
Shape of y: (8, 1)


In [43]:
# Visualizing the forward pass
print("Input",X[0])
print("Shape of Input",X[0].shape)

print("Reshape Input",X[0].reshape(-1,1).shape)
w1=np.random.randn(1,2)
print("Weight",w1)
b1=np.random.randn(1,1)
print("Bias",b1)
z=np.dot(w1,X[0].reshape(-1,1))+b1
print("Z",z)
z=np.tanh(z)
print("Z after activation",z)


Input [1 2]
Shape of Input (2,)
Reshape Input (2, 1)
Weight [[ 0.82254491 -1.22084365]]
Bias [[0.2088636]]
Z [[-1.41027879]]
Z after activation [[-0.88755332]]


In [2]:
#Important Resources-
# https://aman.ai/primers/ai/top-30-papers/
# https://karpathy.github.io/2019/04/25/recipe/